---
title: "Replication of Study How Quick Decisions Illuminate Moral Character by Clayton R. Critcher, Yoel Inbar and David A. Pizarro (2013, Social Psychological and Personality Science)"
author: "Erika Garza-Elorduy (egarzaelorduy@ucsd.edu)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
format:
  html:
    toc: true
    toc_depth: 3
---

## Introduction

The study by Critcher et al. (2013) explores how the speed of decision-making influences how we perceive others’ moral character. The findings suggest that quick decisions may signal a stronger sense of certainty, making someone seem either more moral or immoral in people’s eyes. This experiment caught my attention because it examines the various factors people, whether consciously or unconsciously, consider when forming judgments about others. It’s fascinating to consider that we often judge people not just for what they do, but how quickly they do it. Replicating this study could help explore whether the connection between decision speed and moral judgments holds true across different contexts, offering new perspectives on how moral evaluations are formed.

To conduct this replication experiment, participants will be presented with scenarios similar to those used in the original study. For example, they will read about two individuals who face a moral dilemma, such as finding a wallet filled with money, and must decide whether to return it or keep it. As in the original study, the key manipulation involves the speed of their decision-making: one individual will make the decision quickly, while the other will take longer to decide. The participants will then rate the moral character of each individual based on the perceived morality of their actions and the decision speed. The study will also include manipulation checks, asking participants how certain they believe each decision-maker was, to ensure that decision speed correlates with perceived certainty.

[GitHub Repository](https://github.com/e-garzaelorduy/critcher2013.git)

[Original Paper](https://github.com/e-garzaelorduy/critcher2013/blob/main/original_paper.pdf)

## Methods

### Power Analysis

Original effect size, power analysis for samples to achieve 80%, 90%, 95% power to detect that effect size.  Considerations of feasibility for selecting planned sample size.

### Planned Sample

Planned sample size and/or termination rule, sampling frame, known demographics if any, preselection rules if any.

### Materials

All materials - can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

### Procedure	

Can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

### Analysis Plan

Can also quote directly, though it is less often spelled out effectively for an analysis strategy section.  The key is to report an analysis strategy that is as close to the original - data cleaning rules, data exclusion rules, covariates, etc. - as possible.  

**Clarify key analysis of interest here**  You can also pre-specify additional analyses you plan to do.

### Differences from Original Study

Explicitly describe known differences in sample, setting, procedure, and analysis plan from original study.  The goal, of course, is to minimize those differences, but differences will inevitably occur.  Also, note whether such differences are anticipated to make a difference based on claims in the original article or subsequent published research on the conditions for obtaining the effect.

### Methods Addendum (Post Data Collection)

You can comment this section out prior to final report with data collection.

#### Actual Sample
  Sample size, demographics, data exclusions based on rules spelled out in analysis plan

#### Differences from pre-data collection methods plan
  Any differences from what was described as the original plan, or “none”.


## Results


### Data preparation

Data preparation following the analysis plan.
	
```{r include=F}
### Data Preparation

#### Load Relevant Libraries and Functions

#### Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Confirmatory analysis

The analyses as specified in the analysis plan.  

*Side-by-side graph with original graph is ideal here*

### Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Replication Attempt

Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt.  None of these need to be long.
